---
- name: Create security group for RDS insance and open PostgreSQL port to the EC2 instance
  ec2_group:
    name: "RDS-{{ simplye_role }}-{{ simplye_instance_name }}"
    description: "Firewall rules for the {{ simplye_role }}-{{ simplye_instance_name }} RDS instance"
    region: "{{ aws_region }}"
    rules:
      - proto: tcp
        from_port: 5432
        to_port: 5432
        cidr_ip: "{{ ec2_private_ip }}/32"
  register: rds_sg
- debug: var=rds_sg.group_id

- name: Create an RDS subnet
  rds_subnet_group:
    state: present
    region: "{{ aws_region }}"
    name: "{{ rds_subnet }}"
    description: "RDS subnet for SimplyE"
    subnets: "{{ subnet_ids }}"

- name: Create a PostgreSQL database in AWS RDS
  local_action:
    module: rds
    command: create
    wait: yes
    wait_timeout: 600

    # Our RDS instance gets a unique name to identify it
    instance_name: "{{ simplye_role }}-{{ simplye_instance_name }}"
    tags:
      Environment: "{{ simplye_environment }}"
      Application: "{{ simplye_role }}"

    # Create a new RDS instance
    region: "{{ aws_region }}"
    instance_type: "{{ rds_instance_type }}"
    db_engine: "{{ rds_db_engine }}"
    size: "{{ rds_size }}"
    subnet: "{{ rds_subnet }}"
    vpc_security_groups: "{{ rds_sg.group_id }}"
    multi_zone: no
    port: 5432

    # Create a database on the instance
    db_name: "{{ psql_db_name }}"
    username: "{{ psql_username }}"
    password: "{{ psql_password }}"
  register: rds

- debug: msg="The db endpoint is {{ rds.instance.endpoint }}"
