---
- name: Copy the logs cat script to host
  copy:
    src: files/logs.sh
    dest: /home/ec2-user/logs.sh
    mode: 0775
  become: yes

- name: Copy the bash start script to host
  copy:
    src: files/bash.sh
    dest: /home/ec2-user/bash.sh
    mode: 0775
  become: yes

- local_action:
    module: ec2
    region: "{{ aws_region }}"
    instance_tags:
      Name: "{{ simplye_role }}-{{ simplye_instance_name }}"
    state: restarted
