---
- name: Write the config.json to the server
  template:
    src: templates/config.json
    dest: "/home/ec2-user"
    owner: ec2-user
    group: ec2-user
    mode: 0666

- local_action:
    module: ec2
    region: "{{ aws_region }}"
    instance_tags:
      Name: "{{ simplye_role }}-{{ simplye_instance_name }}"
    state: restarted
