---
- name: Write the config.json to the server
  template:
    src: templates/config.j2
    dest: "/home/ec2-user/config.json"
    owner: ec2-user
    group: ec2-user
    mode: 0666

- name: Pull and start scripts container
  docker_container:
    name: "circ-scripts"
    pull: true
    image: "{{ docker_scripts }}:{{ docker_scripts_tag }}"
    state: started
    env:
        LIBSIMPLE_DB_INIT: "{{ initialize_db }}"
    volumes:
      - /home/ec2-user:/etc/circulation

- name: Pull and start circulation manager deployment container
  docker_container:
    name: "circ-deploy"
    pull: true
    image: "{{ docker_deploy }}:{{ docker_deploy_tag }}"
    state: started
    expose:
      - 80
    ports:
      - "80:80"
    env:
        LIBSIMPLE_DB_INIT: "{{ initialize_db }}"
    volumes:
      - /home/ec2-user:/etc/circulation
