---
- name: Configure Elasticsearch YUM repository
  yum_repository:
    name: elasticsearch-1.7
    description: Elasticsearch 1.7 CentOS repository
    baseurl: http://packages.elastic.co/elasticsearch/1.7/centos
    gpgkey: http://packages.elastic.co/GPG-KEY-elasticsearch
    gpgcheck: yes

- name: Install yum package dependencies
  yum: name=elasticsearch,python27,python27-devel,python-nose,python-pip,docker state=latest

- name: Make sure elasticsearch is running and configured to start at boot
  service:
    name: elasticsearch
    state: started
    enabled: yes
