---
- name: Upgrade all packages
  yum: name=* state=latest

- name: Install the 'Development tools' package group
  yum: name="@Development Tools" state=present

- name: Configure Elasticsearch YUM repository
  yum_repository:
    name: elasticsearch-1.7
    description: Elasticsearch 1.7 CentOS repository
    baseurl: http://packages.elastic.co/elasticsearch/1.7/centos
    gpgkey: http://packages.elastic.co/GPG-KEY-elasticsearch
    gpgcheck: yes

- name: Install yum package dependencies
  yum: name=java-1.8.0-openjdk.x86_64,cairo,elasticsearch,libffi-devel,openssl-devel,python27,python27-devel,python-nose,python-sqlalchemy,python-pip state=latest

- name: Make sure elasticsearch is running and configured to start at boot
  service:
    name: elasticsearch
    state: started
    enabled: yes
